FUNC LABEL 0
    MOV REG 0 VAL 3
    MOV STK A REG 0
    MOV REG 1 VAL 4
    ADD REG 0 REG 1
    CAL VAL 2
    CAL VAL 4
    CAL VAL 3
    RET
FUNC LABEL 2
    MOV REG 0 VAL 7
    ADD REG 0 REG 1
    CAL VAL 7
    PRINT REG 0
    CAL VAL 5
    RET
FUNC LABEL 4
    MOV REG 1 VAL 3
    MOV STK A REG 1
    PRINT STK A
    NOT REG 1
    PRINT REG 1
    CAL VAL 7
    PRINT VAL 0
    CAL VAL 5
    RET
FUNC LABEL 3
    ADD REG 0 REG 1
    PRINT REG 0
    PRINT REG 1
    CAL VAL 7
    CAL VAL 7
    CAL VAL 5
    RET
FUNC LABEL 7
    MOV STK A REG 0
    PRINT STK A
    ADD REG 0 REG 1
    PRINT REG 0
    RET
FUNC LABEL 5
    PRINT REG 0
    PRINT REG 1
    RET
