FUNC LABEL 0
    MOV STK A VAL 0
    MOV REG 0 VAL 2
    MOV REG 1 STK A
    PRINT STK A
    PRINT REG 0
    CAL VAL 3
    RET
FUNC LABEL 3
    ADD REG 0 REG 1
    PRINT REG 0
    PRINT STK A
    RET
