FUNC LABEL 0
    MOV REG 0 VAL 10
    MOV STK A REG 0
    MOV STK B STK A
    CAL VAL 5
    CAL VAL 3
    CAL VAL 7
    PRINT STK A
    RET
FUNC LABEL 3
    MOV STK A VAL 3
    REF STK B STK A
    PRINT PTR B
    RET
FUNC LABEL 5
    MOV STK A VAL 41
    MOV STK B VAL 93
    REF STK C STK A
    PRINT PTR C
    RET
FUNC LABEL 7
    MOV REG 0 VAL 4
    MOV REG 1 VAL 3
    ADD REG 0 REG 1
    PRINT REG 0
    RET
